type Query {
  car(id: ID!): User
  cars: [User]
}

type Car @key(fields: "id") {
  id: ID!
  model: String!
}

input CarInput {
  model: String!
}

type Mutation {
  addCar(carInput: CarInput!): Car
  removeCar(id: ID!): Boolean
}
