version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./.data:/data/db
    ports:
      - '27018:27017'
    command: mongod --quiet --logpath /dev/null 
  user:
    build:
      context: .
      dockerfile: ./user/Dockerfile
    volumes:
      - ./user:/home/node/app/
    container_name: user
    command: yarn watch
    environment:
      - port=4001
    expose:
      - '4001'
    ports:
      - '4001:4001'
  car:
    build:
      context: .
      dockerfile: ./car/Dockerfile
    volumes:
      - ./car:/home/node/app/
    container_name: car
    command: yarn watch
    environment:
      - port=4002
    expose:
      - '4002'
    ports:
      - '4002:4002'
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    volumes:
      - ./gateway:/home/node/app/
    container_name: gateway
    command: yarn watch
    environment:
      - port=4000
      - SERVICE_user=http://user:4001
      - SERVICE_car=http://car:4002
    expose:
      - '4000'
    ports:
      - '4000:4000'
    depends_on:
      - user
      - car