type Query {
  car(id: ID!): Car
  cars: [Car]
}

type Car @key(fields: "id userId") {
  id: ID!
  model: String!
  userId: ID
  user: User
}

input CarInput {
  model: String!
  userId: String!
}

type Mutation {
  addCar(carInput: CarInput!): Car
  updateCar(id: ID!): Car
  removeCar(id: ID!): Boolean
}

extend type User @key(fields: "id") {
  id: ID! @external
  cars: [Car]
}
