import { useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useUsersQuery } from "../generated/graphql";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data } = useUsersQuery();
  const { users } = data || {};

  return (
    <div className={styles.container}>
      <Head>
        <title>React Meetup Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>React Meetup Demo</h1>

        <div className={styles.grid}>
          {users &&
            users.map((user) => (
              <div key={user.id}>
                <Link href={`/users/${user.id}`}>
                  <a className={styles.card}>
                    <p>{user.username}</p>
                  </a>
                </Link>
              </div>
            ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
