type Query {
  user(id: ID!): User
  users: [User]
}

type User @key(fields: "id") {
  id: ID!
  username: String!
}

input UserInput {
  username: String!
}

type Mutation {
  addUser(userInput: UserInput!): User
  updateUser(id: ID!): User
  removeUser(id: ID!): ID
}
